### ISSUE TITLE
Diet page state issue

### ISSUE THREAD

**Issue by MitchellSlavik** [ohdzdev/NutritionSystem#16]
**Describe the bug**
Diet is not saving some values when save is clicked.

**To Reproduce**
![issue](https://user-images.githubusercontent.com/10478484/58372155-4744aa80-7edf-11e9-891b-aeb674400b50.gif)

**Expected behavior**
It to save the changed values.

**Comment by ColinKrist** [comment]
after doing research, this is due to `enableReinitialize` in DietForm.jsx line 29~. A setState is being called on submit button to enable the dialog to appear. This is changing due to a deep equality difference since we have a different form state compared to the original values. To avoid this, I can disable this.
